import ANSWER_FIELDS from 'utils/constants/field/answer';
import QUESTION_FIELDS from 'utils/constants/field/question';

export const QUESTION_NAMES = {
    LEVEL: `${QUESTION_FIELDS.THIS}.${QUESTION_FIELDS.LEVEL}`,
    CORRECT: `${QUESTION_FIELDS.THIS}.${QUESTION_FIELDS.CORRECT}`,
    CATEGORIES: `${QUESTION_FIELDS.THIS}.${QUESTION_FIELDS.CATEGORIES}`,
    DESCRIPTION: `${QUESTION_FIELDS.THIS}.${QUESTION_FIELDS.DESCRIPTION}`
};

export const ANSWER_NAMES = {
    DESCRIPTION: `${ANSWER_FIELDS.THIS}.${ANSWER_FIELDS.DESCRIPTION}`
};
